/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Reservasi;

import Sesi.SessionManager;
import com.sun.jdi.connect.spi.Connection;
import database.CommonConstants;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import database.MyJDBC;
import java.util.Date;

/**
 *
 * @author lala_
 */


public class reservasi extends javax.swing.JPanel {

    public final MyJDBC query = new MyJDBC();
    private int idPelanggan; //variabel untuk menyimpan idPelanggan yang melakukan reservasi
    
    public reservasi() {
        initComponents();
        
        //idPelanggan dari session
        idPelanggan = SessionManager.idPelanggan; 
        
         // Ambil nama pelanggan dari database
         String namaPelanggan = query.getNamaPelanggan(idPelanggan);

         // Menampilkan nama pelanggan jika tersedia
         if (!namaPelanggan.isEmpty()) {
             namaTF.setText(namaPelanggan);
             namaTF.setEditable(true); // aktifkan input agar nama bisa diubah
         } else {
         JOptionPane.showMessageDialog(this, "Nama pelanggan tidak ditemukan. Silakan login ulang.", "Peringatan", JOptionPane.WARNING_MESSAGE);
         }
         
         
        // Set tabel tidak dapat diedit
        tabelLayanan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                    "ID Layanan", "Jenis Layanan", "Nama Layanan", "Deskripsi", "Harga"
                })
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // tidak bisa diedit
            }
        });

        MyJDBC.loadTableDataLayanan(tabelLayanan);
       
        // Setting tanggal yang bisa dipilih tanggal dari hari ini (sebelum hari ini gabisa)
        tanggalReservasiDATE.setMinSelectableDate(new java.util.Date());
    }
    
    // Fungsi untuk menyimpan data dan membersihkan inputan
    private void simpanData() {
        // Menambahkan data ke tabel dengan memanggil method tambahKetabel
        tambahKeTabel();

        // Membersihkan input setelah data disimpan
        bersihkanInput();
    }
    
    // Fungsi untuk membersihkan input
    private void bersihkanInput() {
        IDLayananTF.setText(""); 
        tanggalReservasiDATE.setDate(null); 
        jamReservasiCB.setSelectedIndex(0); 
        namaPegawaiCB.setSelectedIndex(0); 
    }
             
    
  // Fungsi untuk menyimpan data reservasi
    private void tambahKeTabel() {
        int idLayanan;
        
        try {
            idLayanan = Integer.parseInt(IDLayananTF.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Layanan harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = namaTF.getText();
        Date tanggalReservasi = tanggalReservasiDATE.getDate();
        String jamReservasi = (String) jamReservasiCB.getSelectedItem();
        String namaPegawai = (String) namaPegawaiCB.getSelectedItem();
        String status = "Proses"; // Set status default

        // Validasi idPelanggan
        if (idPelanggan == 0) {
            JOptionPane.showMessageDialog(this, "ID pelanggan tidak valid. Silakan login ulang.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi input lainnya
        if (nama.isEmpty() || tanggalReservasi == null) {
            JOptionPane.showMessageDialog(this, "Ada data yang kosong. Mohon isi nama dan tanggal reservasi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jamReservasi == null || jamReservasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jam reservasi harus dipilih.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (namaPegawai == null || namaPegawai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pegawai harus dipilih.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Simpan data ke database dengan
        query.insertReservasi(idPelanggan, idLayanan, nama, tanggalReservasi, jamReservasi, namaPegawai, status, tabelLayanan);

        // Bersihkan input setelah melakukan reservasi
        bersihkanInput();

        // Memuat ulang data layanan di tabel setelah melakukan reservaso
        MyJDBC.loadTableDataLayanan(tabelLayanan);
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IDLayananTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaPegawaiCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tanggalReservasiDATE = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jamReservasiCB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelLayanan = new JTableCustom.jtable_custom();
        ReservasiBT = new javax.swing.JButton();
        namaTF = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1139, 661));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1139, 661));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 73, 73));
        jLabel2.setText("Reservasi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        IDLayananTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(174, 57, 156)));
        IDLayananTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLayananTFActionPerformed(evt);
            }
        });
        jPanel1.add(IDLayananTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nama Pegawai");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 150, 30));

        namaPegawaiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lala", "Delia", "Jia", "Pipah", " " }));
        namaPegawaiCB.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(174, 57, 156)));
        namaPegawaiCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPegawaiCBActionPerformed(evt);
            }
        });
        jPanel1.add(namaPegawaiCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID Layanan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 157, 120, 30));
        jPanel1.add(tanggalReservasiDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Reservasi");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Jam Reservasi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 30));

        jamReservasiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00" }));
        jamReservasiCB.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(174, 57, 156)));
        jamReservasiCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamReservasiCBActionPerformed(evt);
            }
        });
        jPanel1.add(jamReservasiCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 200, 40));

        tabelLayanan.setBackground(new java.awt.Color(255, 204, 204));
        tabelLayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Layanan", "Jenis Layanan", "Nama Layanan", "Deskripsi", "Harga"
            }
        ));
        tabelLayanan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelLayanan.setGridColor(new java.awt.Color(255, 255, 255));
        tabelLayanan.setRowHeight(35);
        tabelLayanan.setRowMargin(1);
        tabelLayanan.setSelectionBackground(new java.awt.Color(153, 102, 0));
        tabelLayanan.setShowGrid(true);
        jScrollPane2.setViewportView(tabelLayanan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 710, 390));

        ReservasiBT.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ReservasiBT.setText("Reservasi");
        ReservasiBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservasiBTMouseClicked(evt);
            }
        });
        ReservasiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasiBTActionPerformed(evt);
            }
        });
        jPanel1.add(ReservasiBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        namaTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(174, 57, 156)));
        namaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTFActionPerformed(evt);
            }
        });
        jPanel1.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 40));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void IDLayananTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLayananTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDLayananTFActionPerformed

    



    private void jamReservasiCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamReservasiCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamReservasiCBActionPerformed

    private void namaPegawaiCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPegawaiCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPegawaiCBActionPerformed

    private void ReservasiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasiBTActionPerformed
        tambahKeTabel();
       
    }//GEN-LAST:event_ReservasiBTActionPerformed

    private void ReservasiBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservasiBTMouseClicked

    }//GEN-LAST:event_ReservasiBTMouseClicked

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTFActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDLayananTF;
    private javax.swing.JButton ReservasiBT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jamReservasiCB;
    private javax.swing.JComboBox<String> namaPegawaiCB;
    private javax.swing.JTextField namaTF;
    private JTableCustom.jtable_custom tabelLayanan;
    private com.toedter.calendar.JDateChooser tanggalReservasiDATE;
    // End of variables declaration//GEN-END:variables

}
