/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author lala_
 */
public class menuPerawatanRambut extends javax.swing.JPanel {

    /**
     * Creates new form menuPotongRambut
     */
    public menuPerawatanRambut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelround3 = new border.panelround();
        jLabel9 = new javax.swing.JLabel();
        panelround2 = new border.panelround();
        jLabel8 = new javax.swing.JLabel();
        panelround4 = new border.panelround();
        jLabel10 = new javax.swing.JLabel();
        panelround5 = new border.panelround();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1139, 661));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1139, 661));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1139, 661));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelround3.setBackground(new java.awt.Color(206, 213, 255));
        panelround3.setRoundBottomLeft(29);
        panelround3.setRoundBottomRight(29);
        panelround3.setRoundTopLeft(29);
        panelround3.setRoundTopRight(29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(149, 73, 73));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Creambath");

        javax.swing.GroupLayout panelround3Layout = new javax.swing.GroupLayout(panelround3);
        panelround3.setLayout(panelround3Layout);
        panelround3Layout.setHorizontalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelround3Layout.setVerticalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(panelround3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 120, 40));

        panelround2.setBackground(new java.awt.Color(206, 213, 255));
        panelround2.setRoundBottomLeft(29);
        panelround2.setRoundBottomRight(29);
        panelround2.setRoundTopLeft(29);
        panelround2.setRoundTopRight(29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 73, 73));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Smoothing");

        javax.swing.GroupLayout panelround2Layout = new javax.swing.GroupLayout(panelround2);
        panelround2.setLayout(panelround2Layout);
        panelround2Layout.setHorizontalGroup(
            panelround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelround2Layout.setVerticalGroup(
            panelround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(panelround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 120, 40));

        panelround4.setBackground(new java.awt.Color(206, 213, 255));
        panelround4.setRoundBottomLeft(29);
        panelround4.setRoundBottomRight(29);
        panelround4.setRoundTopLeft(29);
        panelround4.setRoundTopRight(29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(149, 73, 73));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hair Mask");

        javax.swing.GroupLayout panelround4Layout = new javax.swing.GroupLayout(panelround4);
        panelround4.setLayout(panelround4Layout);
        panelround4Layout.setHorizontalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelround4Layout.setVerticalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(panelround4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 110, 40));

        panelround5.setBackground(new java.awt.Color(206, 213, 255));
        panelround5.setRoundBottomLeft(29);
        panelround5.setRoundBottomRight(29);
        panelround5.setRoundTopLeft(29);
        panelround5.setRoundTopRight(29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 73, 73));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Rebonding");

        javax.swing.GroupLayout panelround5Layout = new javax.swing.GroupLayout(panelround5);
        panelround5.setLayout(panelround5Layout);
        panelround5Layout.setHorizontalGroup(
            panelround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(20, 20, 20))
        );
        panelround5Layout.setVerticalGroup(
            panelround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(panelround5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 120, 40));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(149, 73, 73));
        jLabel15.setText("Rp. 100.000");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 170, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(149, 73, 73));
        jLabel16.setText("Rp. 200.000");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 180, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(149, 73, 73));
        jLabel17.setText("Rp. 170.000");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 180, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 54, 67));
        jLabel22.setText("<html> Meluruskan rambut secara <br> permanen,  cocok untuk rambut <br> sangat keriting. </html>");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 230, 70));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 54, 67));
        jLabel23.setText("<html>Perawatan dengan krim rambut <br> untuk melembutkan, menutrisi, <br> dan melembapkan.</html>");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 230, 70));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 54, 67));
        jLabel24.setText("<html>Masker rambut untuk perbaikan <br> rambut rusak dan menjaga kesehatan rambut.</html>");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 220, 70));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 54, 67));
        jLabel25.setText("<html>Meluruskan rambut dengan hasil <br> lebih natural dibanding rebonding.</html>");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, 50));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(149, 73, 73));
        jLabel14.setText("Rp. 150.000");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 180, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Smothing.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 470, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Creambath.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 470, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Rebonding.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 440, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Hair Mask.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 440, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(149, 73, 73));
        jLabel3.setText("Perawatan Rambut");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private border.panelround panelround2;
    private border.panelround panelround3;
    private border.panelround panelround4;
    private border.panelround panelround5;
    // End of variables declaration//GEN-END:variables
}
