/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author lala_
 */
public class menuWarnaRambut extends javax.swing.JPanel {

    /**
     * Creates new form menuPotongRambut
     */
    public menuWarnaRambut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelround3 = new border.panelround();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelround4 = new border.panelround();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelround5 = new border.panelround();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelround6 = new border.panelround();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelround8 = new border.panelround();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelround9 = new border.panelround();
        jLabel18 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelround10 = new border.panelround();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelround11 = new border.panelround();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1139, 661));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1139, 661));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 73, 73));
        jLabel2.setText("Warna Rambut");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1139, 661));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelround3.setBackground(new java.awt.Color(206, 213, 255));
        panelround3.setRoundBottomLeft(29);
        panelround3.setRoundBottomRight(29);
        panelround3.setRoundTopLeft(29);
        panelround3.setRoundTopRight(29);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 73, 73));
        jLabel11.setText("Ash Purple");

        javax.swing.GroupLayout panelround3Layout = new javax.swing.GroupLayout(panelround3);
        panelround3.setLayout(panelround3Layout);
        panelround3Layout.setHorizontalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround3Layout.setVerticalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, 30));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(149, 73, 73));
        jLabel23.setText("Rp. 100.000");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ashPurple.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        panelround4.setBackground(new java.awt.Color(206, 213, 255));
        panelround4.setRoundBottomLeft(29);
        panelround4.setRoundBottomRight(29);
        panelround4.setRoundTopLeft(29);
        panelround4.setRoundTopRight(29);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(149, 73, 73));
        jLabel12.setText("Ash Blonde");

        javax.swing.GroupLayout panelround4Layout = new javax.swing.GroupLayout(panelround4);
        panelround4.setLayout(panelround4Layout);
        panelround4Layout.setHorizontalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround4Layout.setVerticalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 100, 30));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(149, 73, 73));
        jLabel24.setText("Rp. 90.000");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/blonde.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        panelround5.setBackground(new java.awt.Color(206, 213, 255));
        panelround5.setRoundBottomLeft(29);
        panelround5.setRoundBottomRight(29);
        panelround5.setRoundTopLeft(29);
        panelround5.setRoundTopRight(29);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(149, 73, 73));
        jLabel13.setText("Ash Blue");

        javax.swing.GroupLayout panelround5Layout = new javax.swing.GroupLayout(panelround5);
        panelround5.setLayout(panelround5Layout);
        panelround5Layout.setHorizontalGroup(
            panelround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround5Layout.setVerticalGroup(
            panelround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 100, 30));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(149, 73, 73));
        jLabel25.setText("Rp. 130.000");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/blue.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        panelround6.setBackground(new java.awt.Color(206, 213, 255));
        panelround6.setRoundBottomLeft(29);
        panelround6.setRoundBottomRight(29);
        panelround6.setRoundTopLeft(29);
        panelround6.setRoundTopRight(29);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(149, 73, 73));
        jLabel14.setText("Red Wine");

        javax.swing.GroupLayout panelround6Layout = new javax.swing.GroupLayout(panelround6);
        panelround6.setLayout(panelround6Layout);
        panelround6Layout.setHorizontalGroup(
            panelround6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround6Layout.setVerticalGroup(
            panelround6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 100, 30));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(149, 73, 73));
        jLabel26.setText("Rp. 150.000");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 70, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/red.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        panelround8.setBackground(new java.awt.Color(206, 213, 255));
        panelround8.setRoundBottomLeft(29);
        panelround8.setRoundBottomRight(29);
        panelround8.setRoundTopLeft(29);
        panelround8.setRoundTopRight(29);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(149, 73, 73));
        jLabel17.setText("Ash Brown");

        javax.swing.GroupLayout panelround8Layout = new javax.swing.GroupLayout(panelround8);
        panelround8.setLayout(panelround8Layout);
        panelround8Layout.setHorizontalGroup(
            panelround8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround8Layout.setVerticalGroup(
            panelround8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 100, 30));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(149, 73, 73));
        jLabel28.setText("Rp. 120.000");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 70, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/brown.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        panelround9.setBackground(new java.awt.Color(206, 213, 255));
        panelround9.setRoundBottomLeft(29);
        panelround9.setRoundBottomRight(29);
        panelround9.setRoundTopLeft(29);
        panelround9.setRoundTopRight(29);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(149, 73, 73));
        jLabel18.setText("Ash Pink");

        javax.swing.GroupLayout panelround9Layout = new javax.swing.GroupLayout(panelround9);
        panelround9.setLayout(panelround9Layout);
        panelround9Layout.setHorizontalGroup(
            panelround9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelround9Layout.setVerticalGroup(
            panelround9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 100, 30));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(149, 73, 73));
        jLabel29.setText("Rp. 170.000");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 70, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pink.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        panelround10.setBackground(new java.awt.Color(206, 213, 255));
        panelround10.setRoundBottomLeft(29);
        panelround10.setRoundBottomRight(29);
        panelround10.setRoundTopLeft(29);
        panelround10.setRoundTopRight(29);

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(149, 73, 73));
        jLabel20.setText("Ash Rainbow");

        javax.swing.GroupLayout panelround10Layout = new javax.swing.GroupLayout(panelround10);
        panelround10.setLayout(panelround10Layout);
        panelround10Layout.setHorizontalGroup(
            panelround10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround10Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround10Layout.setVerticalGroup(
            panelround10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 100, 30));

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(149, 73, 73));
        jLabel30.setText("Rp. 200.000");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 70, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rainbow.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        panelround11.setBackground(new java.awt.Color(206, 213, 255));
        panelround11.setRoundBottomLeft(29);
        panelround11.setRoundBottomRight(29);
        panelround11.setRoundTopLeft(29);
        panelround11.setRoundTopRight(29);

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(149, 73, 73));
        jLabel31.setText("Ash Grey");

        javax.swing.GroupLayout panelround11Layout = new javax.swing.GroupLayout(panelround11);
        panelround11.setLayout(panelround11Layout);
        panelround11Layout.setHorizontalGroup(
            panelround11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround11Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelround11Layout.setVerticalGroup(
            panelround11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelround11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 100, 30));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(149, 73, 73));
        jLabel32.setText("Rp. 130.000");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 70, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/grey.png"))); // NOI18N
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private border.panelround panelround10;
    private border.panelround panelround11;
    private border.panelround panelround3;
    private border.panelround panelround4;
    private border.panelround panelround5;
    private border.panelround panelround6;
    private border.panelround panelround8;
    private border.panelround panelround9;
    // End of variables declaration//GEN-END:variables
}
