/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author lala_
 */
public class menuPotongRambut extends javax.swing.JPanel {

    /**
     * Creates new form menuPotongRambut
     */
    public menuPotongRambut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelround1 = new border.panelround();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelround2 = new border.panelround();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelround3 = new border.panelround();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelround4 = new border.panelround();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        panelround5 = new border.panelround();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelround6 = new border.panelround();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1139, 661));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1139, 661));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelround1.setBackground(new java.awt.Color(206, 213, 255));
        panelround1.setRoundBottomLeft(29);
        panelround1.setRoundBottomRight(29);
        panelround1.setRoundTopLeft(29);
        panelround1.setRoundTopRight(29);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(149, 73, 73));
        jLabel9.setText("Bob Haircut");

        javax.swing.GroupLayout panelround1Layout = new javax.swing.GroupLayout(panelround1);
        panelround1.setLayout(panelround1Layout);
        panelround1Layout.setHorizontalGroup(
            panelround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelround1Layout.setVerticalGroup(
            panelround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 120, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(149, 73, 73));
        jLabel15.setText("Rp. 100.000");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 90, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(149, 73, 73));
        jLabel21.setText("Rp. 120.000");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 54, 67));
        jLabel22.setText("<html>cocok untuk wajah<br>oval dan panjang</html>");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 120, 70));

        panelround2.setBackground(new java.awt.Color(206, 213, 255));
        panelround2.setRoundBottomLeft(29);
        panelround2.setRoundBottomRight(29);
        panelround2.setRoundTopLeft(29);
        panelround2.setRoundTopRight(29);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 73, 73));
        jLabel8.setText("Butterfly Haircut");

        javax.swing.GroupLayout panelround2Layout = new javax.swing.GroupLayout(panelround2);
        panelround2.setLayout(panelround2Layout);
        panelround2Layout.setHorizontalGroup(
            panelround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelround2Layout.setVerticalGroup(
            panelround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(149, 73, 73));
        jLabel14.setText("Rp. 110.000");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 80, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 54, 67));
        jLabel20.setText("<html>cocok untuk wajah<br>oval, dan bulat</html>");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 120, 70));

        panelround3.setBackground(new java.awt.Color(206, 213, 255));
        panelround3.setRoundBottomLeft(29);
        panelround3.setRoundBottomRight(29);
        panelround3.setRoundTopLeft(29);
        panelround3.setRoundTopRight(29);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(149, 73, 73));
        jLabel10.setText("Hime Haircut");

        javax.swing.GroupLayout panelround3Layout = new javax.swing.GroupLayout(panelround3);
        panelround3.setLayout(panelround3Layout);
        panelround3Layout.setHorizontalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelround3Layout.setVerticalGroup(
            panelround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelround3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 120, 30));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(149, 73, 73));
        jLabel16.setText("Rp. 140.000");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 54, 67));
        jLabel23.setText("<html>cocok untuk wajah<br>oval, hati dan <br> persegi</html>");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 100, 50));

        panelround4.setBackground(new java.awt.Color(206, 213, 255));
        panelround4.setRoundBottomLeft(29);
        panelround4.setRoundBottomRight(29);
        panelround4.setRoundTopLeft(29);
        panelround4.setRoundTopRight(29);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 73, 73));
        jLabel11.setText("Wavy Haircut");

        javax.swing.GroupLayout panelround4Layout = new javax.swing.GroupLayout(panelround4);
        panelround4.setLayout(panelround4Layout);
        panelround4Layout.setHorizontalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelround4Layout.setVerticalGroup(
            panelround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelround4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, 30));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 54, 67));
        jLabel24.setText("<html>cocok untuk wajah<br>oval / lonjong</html>");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 120, 70));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 54, 67));
        jLabel25.setText("<html>cocok untuk wajah<br>oval, bulat, dan <br> panjang</html>");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 120, 60));

        panelround5.setBackground(new java.awt.Color(206, 213, 255));
        panelround5.setRoundBottomLeft(29);
        panelround5.setRoundBottomRight(29);
        panelround5.setRoundTopLeft(29);
        panelround5.setRoundTopRight(29);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(149, 73, 73));
        jLabel12.setText("Wolf Haircut");

        javax.swing.GroupLayout panelround5Layout = new javax.swing.GroupLayout(panelround5);
        panelround5.setLayout(panelround5Layout);
        panelround5Layout.setHorizontalGroup(
            panelround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelround5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelround5Layout.setVerticalGroup(
            panelround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(panelround5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 130, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(149, 73, 73));
        jLabel18.setText("Rp. 130.000");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 54, 67));
        jLabel26.setText("<html>cocok untuk wajah<br>bulat, oval, hati, <br> dan tirus</html>");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 120, 60));

        panelround6.setBackground(new java.awt.Color(206, 213, 255));
        panelround6.setRoundBottomLeft(29);
        panelround6.setRoundBottomRight(29);
        panelround6.setRoundTopLeft(29);
        panelround6.setRoundTopRight(29);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(149, 73, 73));
        jLabel13.setText(" Pixie Haircut");

        javax.swing.GroupLayout panelround6Layout = new javax.swing.GroupLayout(panelround6);
        panelround6.setLayout(panelround6Layout);
        panelround6Layout.setHorizontalGroup(
            panelround6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelround6Layout.setVerticalGroup(
            panelround6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelround6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelround6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 130, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(149, 73, 73));
        jLabel19.setText("Rp. 120.000");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Bob.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 73, 73));
        jLabel2.setText("Model Potongan Rambut");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Butterfly Cut.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 310, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Wavy.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 391, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Wolfcut.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pixie.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Hime.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private border.panelround panelround1;
    private border.panelround panelround2;
    private border.panelround panelround3;
    private border.panelround panelround4;
    private border.panelround panelround5;
    private border.panelround panelround6;
    // End of variables declaration//GEN-END:variables
}
