/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import Login.FormLogin;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;
import view.menuPotongRambut;
import view.menuWarnaRambut;
import view.menuPerawatanRambut;
import Reservasi.reservasi;
import Reservasi.riwayatReservasi;
import Sesi.SessionManager;
import javax.swing.JOptionPane;
import view.beranda;

/**
 *
 * @author lala_
 */
public class menu extends javax.swing.JFrame {

    int xx, xy;
    private Timer timer;
    
    public menu() {
        initComponents();
        setDate();
        pn_utama.removeAll();
        pn_utama.add(new beranda());
        
    }
    
    private void setDate(){
        timer = new Timer(1000, new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e) {
               Calendar calender = Calendar.getInstance();
               Date now = new Date();
               SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
               SimpleDateFormat formatTanggal = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
               String hari = formatHari.format(calender.getTime());
               String waktuTanggal = formatTanggal.format(now);
               dateLB.setText(hari+", "+waktuTanggal);
           }
        }); 
        
        timer.start();
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        layananLB = new javax.swing.JLabel();
        pn_buttonPotongRambut = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PotongRambutBT = new javax.swing.JLabel();
        pn_buttonWarnaRambut = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        WarnaRambutBT = new javax.swing.JLabel();
        pn_buttonPerawatanRambut = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PerawatanRambutBT = new javax.swing.JLabel();
        reservasiLB = new javax.swing.JLabel();
        pn_buttonReservasi = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        reservasiBT = new javax.swing.JLabel();
        pn_buttonKeluar = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        keluarBT = new javax.swing.JLabel();
        pn_buttonRiwayatReservasi = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        riwayatReservasiBT = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dateLB = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(250, 213, 219));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 769));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_house_50px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Beranda");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        layananLB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        layananLB.setForeground(new java.awt.Color(153, 153, 153));
        layananLB.setText("LAYANAN");

        pn_buttonPotongRambut.setBackground(new java.awt.Color(255, 255, 255));

        pn_line.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_barbershop_37px_1.png"))); // NOI18N

        PotongRambutBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PotongRambutBT.setForeground(new java.awt.Color(102, 102, 102));
        PotongRambutBT.setText("Potong Rambut");
        PotongRambutBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PotongRambutBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PotongRambutBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PotongRambutBTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_buttonPotongRambutLayout = new javax.swing.GroupLayout(pn_buttonPotongRambut);
        pn_buttonPotongRambut.setLayout(pn_buttonPotongRambutLayout);
        pn_buttonPotongRambutLayout.setHorizontalGroup(
            pn_buttonPotongRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonPotongRambutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PotongRambutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(pn_buttonPotongRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonPotongRambutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        pn_buttonPotongRambutLayout.setVerticalGroup(
            pn_buttonPotongRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonPotongRambutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buttonPotongRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PotongRambutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_buttonPotongRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonPotongRambutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_buttonWarnaRambut.setBackground(new java.awt.Color(255, 255, 255));

        pn_line1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_nerd_hair_37px.png"))); // NOI18N

        WarnaRambutBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WarnaRambutBT.setForeground(new java.awt.Color(102, 102, 102));
        WarnaRambutBT.setText("Warna Rambut");
        WarnaRambutBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WarnaRambutBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WarnaRambutBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WarnaRambutBTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_buttonWarnaRambutLayout = new javax.swing.GroupLayout(pn_buttonWarnaRambut);
        pn_buttonWarnaRambut.setLayout(pn_buttonWarnaRambutLayout);
        pn_buttonWarnaRambutLayout.setHorizontalGroup(
            pn_buttonWarnaRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonWarnaRambutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WarnaRambutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(pn_buttonWarnaRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonWarnaRambutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
        );
        pn_buttonWarnaRambutLayout.setVerticalGroup(
            pn_buttonWarnaRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonWarnaRambutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buttonWarnaRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WarnaRambutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_buttonWarnaRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonWarnaRambutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_buttonPerawatanRambut.setBackground(new java.awt.Color(255, 255, 255));

        pn_line2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_straight_razor_37px.png"))); // NOI18N

        PerawatanRambutBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PerawatanRambutBT.setForeground(new java.awt.Color(102, 102, 102));
        PerawatanRambutBT.setText("Perawatan Rambut");
        PerawatanRambutBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerawatanRambutBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PerawatanRambutBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PerawatanRambutBTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_buttonPerawatanRambutLayout = new javax.swing.GroupLayout(pn_buttonPerawatanRambut);
        pn_buttonPerawatanRambut.setLayout(pn_buttonPerawatanRambutLayout);
        pn_buttonPerawatanRambutLayout.setHorizontalGroup(
            pn_buttonPerawatanRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonPerawatanRambutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PerawatanRambutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_buttonPerawatanRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonPerawatanRambutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        pn_buttonPerawatanRambutLayout.setVerticalGroup(
            pn_buttonPerawatanRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonPerawatanRambutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buttonPerawatanRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PerawatanRambutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_buttonPerawatanRambutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonPerawatanRambutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        reservasiLB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        reservasiLB.setForeground(new java.awt.Color(153, 153, 153));
        reservasiLB.setText("RESERVASI");

        pn_buttonReservasi.setBackground(new java.awt.Color(255, 255, 255));

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_wing_chair_37px.png"))); // NOI18N

        reservasiBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservasiBT.setForeground(new java.awt.Color(102, 102, 102));
        reservasiBT.setText("Reservasi Hair Salon");
        reservasiBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasiBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservasiBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservasiBTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_buttonReservasiLayout = new javax.swing.GroupLayout(pn_buttonReservasi);
        pn_buttonReservasi.setLayout(pn_buttonReservasiLayout);
        pn_buttonReservasiLayout.setHorizontalGroup(
            pn_buttonReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonReservasiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(pn_buttonReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonReservasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        pn_buttonReservasiLayout.setVerticalGroup(
            pn_buttonReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonReservasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buttonReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(reservasiBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_buttonReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonReservasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        pn_buttonKeluar.setBackground(new java.awt.Color(255, 255, 255));

        pn_line4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_exit_37px.png"))); // NOI18N

        keluarBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        keluarBT.setForeground(new java.awt.Color(102, 102, 102));
        keluarBT.setText("Keluar");
        keluarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keluarBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                keluarBTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_buttonKeluarLayout = new javax.swing.GroupLayout(pn_buttonKeluar);
        pn_buttonKeluar.setLayout(pn_buttonKeluarLayout);
        pn_buttonKeluarLayout.setHorizontalGroup(
            pn_buttonKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonKeluarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_buttonKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonKeluarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        pn_buttonKeluarLayout.setVerticalGroup(
            pn_buttonKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buttonKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keluarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_buttonKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonKeluarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_buttonRiwayatReservasi.setBackground(new java.awt.Color(255, 255, 255));

        pn_line5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_books_37px.png"))); // NOI18N

        riwayatReservasiBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        riwayatReservasiBT.setForeground(new java.awt.Color(102, 102, 102));
        riwayatReservasiBT.setText("Riwayat Reservasi");
        riwayatReservasiBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatReservasiBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatReservasiBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatReservasiBTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_buttonRiwayatReservasiLayout = new javax.swing.GroupLayout(pn_buttonRiwayatReservasi);
        pn_buttonRiwayatReservasi.setLayout(pn_buttonRiwayatReservasiLayout);
        pn_buttonRiwayatReservasiLayout.setHorizontalGroup(
            pn_buttonRiwayatReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonRiwayatReservasiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riwayatReservasiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_buttonRiwayatReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonRiwayatReservasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );
        pn_buttonRiwayatReservasiLayout.setVerticalGroup(
            pn_buttonRiwayatReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buttonRiwayatReservasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buttonRiwayatReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(riwayatReservasiBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_buttonRiwayatReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_buttonRiwayatReservasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(reservasiLB, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(layananLB, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn_buttonRiwayatReservasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_buttonReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_buttonPerawatanRambut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_buttonPotongRambut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_kiriLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pn_buttonWarnaRambut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_buttonKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(layananLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_buttonPotongRambut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_buttonWarnaRambut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_buttonPerawatanRambut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reservasiLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_buttonReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_buttonRiwayatReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(250, 213, 219));

        dateLB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dateLB.setForeground(new java.awt.Color(102, 102, 102));
        dateLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLB.setText("Date");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_star_50px.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("ReStar");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Hair Salon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(890, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dateLB, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pn_kanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);
        pn_kanan.add(jLabel10, java.awt.BorderLayout.PAGE_END);

        pn_dasar.setBackground(new java.awt.Color(245, 245, 245));
        pn_dasar.setPreferredSize(new java.awt.Dimension(1139, 661));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setPreferredSize(new java.awt.Dimension(1139, 661));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PotongRambutBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PotongRambutBTMouseEntered
        pn_buttonPotongRambut.setBackground(new Color(250, 250, 250));
        pn_line.setBackground(new Color(250, 213, 219));

    }//GEN-LAST:event_PotongRambutBTMouseEntered

    private void PotongRambutBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PotongRambutBTMouseExited
        pn_buttonPotongRambut.setBackground(new Color(255, 255, 255));
        pn_line.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PotongRambutBTMouseExited

    private void PotongRambutBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PotongRambutBTMouseClicked
        pn_buttonPotongRambut.setBackground(new Color(240, 240, 240));
        pn_line.setBackground(new Color(250, 213, 219));
        
        pn_utama.removeAll();
        pn_utama.add(new menuPotongRambut());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_PotongRambutBTMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged
    private void WarnaRambutBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarnaRambutBTMouseClicked
        pn_buttonWarnaRambut.setBackground(new Color(240, 240, 240));
        pn_line1.setBackground(new Color(250, 213, 219));
        
        pn_utama.removeAll();
        pn_utama.add(new menuWarnaRambut());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_WarnaRambutBTMouseClicked

    private void WarnaRambutBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarnaRambutBTMouseEntered
        pn_buttonWarnaRambut.setBackground(new Color(250, 250, 250));
        pn_line1.setBackground(new Color(250, 213, 219));
    }//GEN-LAST:event_WarnaRambutBTMouseEntered

    private void WarnaRambutBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarnaRambutBTMouseExited
        pn_buttonWarnaRambut.setBackground(new Color(255, 255, 255));
        pn_line1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_WarnaRambutBTMouseExited

    private void PerawatanRambutBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerawatanRambutBTMouseClicked
        pn_buttonPerawatanRambut.setBackground(new Color(240, 240, 240));
        pn_line2.setBackground(new Color(250, 213, 219));
        
        pn_utama.removeAll();
        pn_utama.add(new menuPerawatanRambut());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_PerawatanRambutBTMouseClicked

    private void PerawatanRambutBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerawatanRambutBTMouseEntered
        pn_buttonPerawatanRambut.setBackground(new Color(250, 250, 250));
        pn_line2.setBackground(new Color(250, 213, 219));
    }//GEN-LAST:event_PerawatanRambutBTMouseEntered

    private void PerawatanRambutBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerawatanRambutBTMouseExited
        pn_buttonPerawatanRambut.setBackground(new Color(255, 255, 255));
        pn_line2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PerawatanRambutBTMouseExited

    private void reservasiBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasiBTMouseClicked
        pn_buttonReservasi.setBackground(new Color(240, 240, 240));
        pn_line3.setBackground(new Color(250, 213, 219));
        
        pn_utama.removeAll();
        pn_utama.add(new reservasi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_reservasiBTMouseClicked

    private void reservasiBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasiBTMouseEntered
        pn_buttonReservasi.setBackground(new Color(250, 250, 250));
        pn_line3.setBackground(new Color(250, 213, 219));
    }//GEN-LAST:event_reservasiBTMouseEntered

    private void reservasiBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasiBTMouseExited
        pn_buttonReservasi.setBackground(new Color(255, 255, 255));
        pn_line3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_reservasiBTMouseExited

    private void keluarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBTMouseClicked
        pn_buttonKeluar.setBackground(new Color(240, 240, 240));
        pn_line4.setBackground(new Color(250, 213, 219));
        
        int respon = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar?", "Konfimasi Keluar",
                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (respon == JOptionPane.YES_OPTION){
            // Mengakhiri sesi dengan mengatur ulang idPelanggan
            SessionManager.idPelanggan = 0; // Atur ulang sesi ke nilai awal
            this.dispose();
            new FormLogin().setVisible(true);
        }
    }//GEN-LAST:event_keluarBTMouseClicked

    private void keluarBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBTMouseEntered
        pn_buttonKeluar.setBackground(new Color(250, 250, 250));
        pn_line4.setBackground(new Color(250, 213, 219));
    }//GEN-LAST:event_keluarBTMouseEntered

    private void keluarBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBTMouseExited
        pn_buttonKeluar.setBackground(new Color(255, 255, 255));
        pn_line4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_keluarBTMouseExited

    private void riwayatReservasiBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatReservasiBTMouseClicked
        pn_buttonRiwayatReservasi.setBackground(new Color(240, 240, 240));
        pn_line5.setBackground(new Color(250, 213, 219));
        
        pn_utama.removeAll();
        pn_utama.add(new riwayatReservasi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_riwayatReservasiBTMouseClicked

    private void riwayatReservasiBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatReservasiBTMouseEntered
        pn_buttonRiwayatReservasi.setBackground(new Color(250, 250, 250));
        pn_line5.setBackground(new Color(250, 213, 219));
    }//GEN-LAST:event_riwayatReservasiBTMouseEntered

    private void riwayatReservasiBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatReservasiBTMouseExited
        pn_buttonRiwayatReservasi.setBackground(new Color(255, 255, 255));
        pn_line5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_riwayatReservasiBTMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        pn_utama.removeAll();
        pn_utama.add(new beranda());
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PerawatanRambutBT;
    private javax.swing.JLabel PotongRambutBT;
    private javax.swing.JLabel WarnaRambutBT;
    private javax.swing.JLabel dateLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel keluarBT;
    private javax.swing.JLabel layananLB;
    private javax.swing.JPanel pn_buttonKeluar;
    private javax.swing.JPanel pn_buttonPerawatanRambut;
    private javax.swing.JPanel pn_buttonPotongRambut;
    private javax.swing.JPanel pn_buttonReservasi;
    private javax.swing.JPanel pn_buttonRiwayatReservasi;
    private javax.swing.JPanel pn_buttonWarnaRambut;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel reservasiBT;
    private javax.swing.JLabel reservasiLB;
    private javax.swing.JLabel riwayatReservasiBT;
    // End of variables declaration//GEN-END:variables
}
