/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import database.MyJDBC;
import javax.swing.JOptionPane;

/**
 *
 * @author lala_
 */
public class FormRegister extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormRegister() {
        initComponents();
        sembunyiKatsanLB.setVisible(false);
        sembunyiKatsanLB1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGradient1 = new JPanelGradient.JPanelGradient();
        jLabel3 = new javax.swing.JLabel();
        panelround1 = new border.panelround();
        lihatKatsanLB = new javax.swing.JLabel();
        sembunyiKatsanLB = new javax.swing.JLabel();
        lihatKatsanLB1 = new javax.swing.JLabel();
        sembunyiKatsanLB1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        konfirKatsanTF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        masukLB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaPenggunaTF = new javax.swing.JTextField();
        daftarBT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        noTelpTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alamatTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        kataSandiTF = new javax.swing.JPasswordField();
        panelround2 = new border.panelround();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelGradient1.setColorEnd(new java.awt.Color(250, 213, 219));
        jPanelGradient1.setColorStart(new java.awt.Color(255, 255, 255));
        jPanelGradient1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelGradient1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelGradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PegawaiSalon.png"))); // NOI18N
        jPanelGradient1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -150, 270, 870));

        panelround1.setBackground(new java.awt.Color(255, 255, 255));
        panelround1.setRoundBottomLeft(40);
        panelround1.setRoundBottomRight(40);
        panelround1.setRoundTopLeft(40);
        panelround1.setRoundTopRight(40);
        panelround1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lihatKatsanLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatKatsanLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eye_30px.png"))); // NOI18N
        lihatKatsanLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatKatsanLBMouseClicked(evt);
            }
        });
        panelround1.add(lihatKatsanLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 40, 50));

        sembunyiKatsanLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sembunyiKatsanLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_invisible_30px.png"))); // NOI18N
        sembunyiKatsanLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sembunyiKatsanLBMouseClicked(evt);
            }
        });
        panelround1.add(sembunyiKatsanLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 40, 50));

        lihatKatsanLB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatKatsanLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eye_30px.png"))); // NOI18N
        lihatKatsanLB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatKatsanLB1MouseClicked(evt);
            }
        });
        panelround1.add(lihatKatsanLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 40, 50));

        sembunyiKatsanLB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sembunyiKatsanLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_invisible_30px.png"))); // NOI18N
        sembunyiKatsanLB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sembunyiKatsanLB1MouseClicked(evt);
            }
        });
        panelround1.add(sembunyiKatsanLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 40, 50));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Kata Sandi");
        panelround1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        konfirKatsanTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        konfirKatsanTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(konfirKatsanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hallo!");
        panelround1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 228, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Sudah memiliki akun?");
        panelround1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        masukLB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        masukLB.setForeground(new java.awt.Color(102, 102, 102));
        masukLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masukLB.setText("Masuk disini");
        masukLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masukLBMouseClicked(evt);
            }
        });
        panelround1.add(masukLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 90, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nama Pengguna");
        panelround1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        namaPenggunaTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        namaPenggunaTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namaPenggunaTF.setToolTipText("");
        namaPenggunaTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(namaPenggunaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 50));

        daftarBT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        daftarBT.setText("Daftar");
        daftarBT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        daftarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBTActionPerformed(evt);
            }
        });
        panelround1.add(daftarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 290, 45));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Konfirmasi Kata Sandi");
        panelround1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nama");
        panelround1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        noTelpTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        noTelpTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        noTelpTF.setToolTipText("");
        noTelpTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(noTelpTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, 50));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No.Telp");
        jLabel9.setToolTipText("");
        panelround1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Alamat");
        panelround1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        alamatTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        alamatTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        alamatTF.setToolTipText("");
        alamatTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(alamatTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 50));

        namaTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        namaTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namaTF.setToolTipText("");
        namaTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 50));

        kataSandiTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kataSandiTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(kataSandiTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 200, 50));

        jPanelGradient1.add(panelround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 470, 480));

        panelround2.setBackground(new java.awt.Color(255, 204, 204));
        panelround2.setRoundBottomLeft(50);
        panelround2.setRoundBottomRight(50);
        panelround2.setRoundTopLeft(50);
        panelround2.setRoundTopRight(50);
        panelround2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelGradient1.add(panelround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 240, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lihatKatsanLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatKatsanLBMouseClicked
        lihatKatsanLB.setVisible(false);
        sembunyiKatsanLB.setVisible(true);
        kataSandiTF.setEchoChar((char)0);
    }//GEN-LAST:event_lihatKatsanLBMouseClicked

    private void sembunyiKatsanLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sembunyiKatsanLBMouseClicked
        lihatKatsanLB.setVisible(true);
        sembunyiKatsanLB.setVisible(false);
        kataSandiTF.setEchoChar('*');
    }//GEN-LAST:event_sembunyiKatsanLBMouseClicked

    private void lihatKatsanLB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatKatsanLB1MouseClicked
        lihatKatsanLB1.setVisible(false);
        sembunyiKatsanLB1.setVisible(true);
        konfirKatsanTF.setEchoChar((char)0);
    }//GEN-LAST:event_lihatKatsanLB1MouseClicked

    private void sembunyiKatsanLB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sembunyiKatsanLB1MouseClicked
        lihatKatsanLB1.setVisible(true);
        sembunyiKatsanLB1.setVisible(false);
        konfirKatsanTF.setEchoChar('*');
    }//GEN-LAST:event_sembunyiKatsanLB1MouseClicked

    private void masukLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukLBMouseClicked

        FormRegister.this.dispose();

        // membuat instance baru dari from Register dan menampilkannya
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_masukLBMouseClicked

    private void daftarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBTActionPerformed
        
        String nama = namaTF.getText();
        String noTelp = noTelpTF.getText();
        String alamat = alamatTF.getText();

        // mengambil input teks dari field usernameTF sebagai username
        String namaPelanggan = namaPenggunaTF.getText();

        // mengambil input teks dari field passwordTF sebagai password dan mengonversinya ke String
        String kataSandi = new String(kataSandiTF.getPassword());
        // mengambil input teks dari field confirmPass dan mengonversinya ke String
        String konfirKatsan = new String(konfirKatsanTF.getPassword());

        // memeriksa apakah panjang username kurang dari 6 karakter
        if (namaPelanggan.length() < 6){
            // menampilkan pesan dialog bahwa username harus minimal 6 karakter.
            JOptionPane.showMessageDialog(FormRegister.this, "Nama Pengguna harus terdiri dari minimal 6 karakter. Silahkan coba lagi.");
            return;  // menghentikan eksekusi metode jika validasi gagal
        }

        // memeriksa apakah password dan confirmPass tidak cocok
        if (!kataSandi.equals(konfirKatsan)){
            // menampilkan pesan dialog bahwa password tidak cocok
            JOptionPane.showMessageDialog(FormRegister.this, "Kata Sandi tidak cocok. Silahkan coba lagi.");
            return;  // menghentikan eksekusi metode jika validasi gagal
        }

        // memanggil metode Register di MyJDBC untuk mendaftarkan pengguna baru
        if (MyJDBC.Register(nama, noTelp, alamat, namaPelanggan, kataSandi)){
            // menutup jendela Register jika pendaftaran berhasil
            FormRegister.this.dispose();
            // membuka jendela login setelah pendaftaran berhasil
            FormLogin login = new FormLogin();
            login.setVisible(true);
            // menampilkan pesan dialog bahwa pendaftaran berhasil
            JOptionPane.showMessageDialog(login, "Akun Anda berhasil didaftarkan!");
        } else {
            // menampilkan pesan bahwa username sudah digunakan
            JOptionPane.showMessageDialog(FormRegister.this, "Pendaftaran gagal. Silahkan coba lagi.");
        }
    }//GEN-LAST:event_daftarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTF;
    private javax.swing.JButton daftarBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private JPanelGradient.JPanelGradient jPanelGradient1;
    private javax.swing.JPasswordField kataSandiTF;
    private javax.swing.JPasswordField konfirKatsanTF;
    private javax.swing.JLabel lihatKatsanLB;
    private javax.swing.JLabel lihatKatsanLB1;
    private javax.swing.JLabel masukLB;
    private javax.swing.JTextField namaPenggunaTF;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField noTelpTF;
    private border.panelround panelround1;
    private border.panelround panelround2;
    private javax.swing.JLabel sembunyiKatsanLB;
    private javax.swing.JLabel sembunyiKatsanLB1;
    // End of variables declaration//GEN-END:variables
}
