/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Reservasi.reservasi;
import Sesi.SessionManager;
import database.MyJDBC;
import javax.swing.JOptionPane;
import menu.menu;
import menu.menuAdmin;

/**
 *
 * @author lala_
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        sembunyiKatsanLB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGradient1 = new JPanelGradient.JPanelGradient();
        jLabel6 = new javax.swing.JLabel();
        panelround2 = new border.panelround();
        panelround1 = new border.panelround();
        lihatKatsanLB = new javax.swing.JLabel();
        sembunyiKatsanLB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        daftarLB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaPenggunaTF = new javax.swing.JTextField();
        masukBT = new javax.swing.JButton();
        kataSandiTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelGradient1.setColorEnd(new java.awt.Color(250, 213, 219));
        jPanelGradient1.setColorStart(new java.awt.Color(255, 255, 255));
        jPanelGradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hallo (310 x 400 piksel) (2).png"))); // NOI18N
        jPanelGradient1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 440, 590));

        panelround2.setBackground(new java.awt.Color(255, 204, 204));
        panelround2.setRoundBottomLeft(50);
        panelround2.setRoundBottomRight(50);
        panelround2.setRoundTopLeft(50);
        panelround2.setRoundTopRight(50);
        panelround2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelGradient1.add(panelround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 410));

        panelround1.setBackground(new java.awt.Color(255, 255, 255));
        panelround1.setRoundBottomLeft(40);
        panelround1.setRoundBottomRight(40);
        panelround1.setRoundTopLeft(40);
        panelround1.setRoundTopRight(40);
        panelround1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lihatKatsanLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatKatsanLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eye_30px.png"))); // NOI18N
        lihatKatsanLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatKatsanLBMouseClicked(evt);
            }
        });
        panelround1.add(lihatKatsanLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 40, 50));

        sembunyiKatsanLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sembunyiKatsanLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_invisible_30px.png"))); // NOI18N
        sembunyiKatsanLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sembunyiKatsanLBMouseClicked(evt);
            }
        });
        panelround1.add(sembunyiKatsanLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 40, 50));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Kata Sandi");
        panelround1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang");
        panelround1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 228, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Belum memiliki akun?");
        panelround1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        daftarLB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        daftarLB.setForeground(new java.awt.Color(102, 102, 102));
        daftarLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daftarLB.setText("Daftar disini");
        daftarLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarLBMouseClicked(evt);
            }
        });
        panelround1.add(daftarLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nama Pengguna");
        panelround1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        namaPenggunaTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        namaPenggunaTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namaPenggunaTF.setToolTipText("");
        namaPenggunaTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        panelround1.add(namaPenggunaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, 50));

        masukBT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        masukBT.setText("Masuk");
        masukBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukBTActionPerformed(evt);
            }
        });
        panelround1.add(masukBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 250, 45));

        kataSandiTF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kataSandiTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(196, 80, 165)));
        kataSandiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kataSandiTFActionPerformed(evt);
            }
        });
        panelround1.add(kataSandiTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 250, 50));

        jPanelGradient1.add(panelround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 380, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masukBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukBTActionPerformed
        String namaPengguna = namaPenggunaTF.getText();
        String kataSandi = new String(kataSandiTF.getPassword());

    // Validasi login customer
    if (MyJDBC.validasiCustomer(namaPengguna, kataSandi)) {
        // Ambil idPelanggan dari SessionManager
        int idPelanggan = SessionManager.idPelanggan;
        

        // Tampilkan pesan keberhasilan login dan memberikan informasi terkait id pelanggan
        JOptionPane.showMessageDialog(this, "Login berhasil! ID Pelanggan Anda adalah: " + idPelanggan);

        // Tampilkan menu utama
        menu tampilMenu = new menu();
        tampilMenu.setVisible(true);
        this.dispose();
        
    } else if (namaPengguna.equals("admin123") && kataSandi.equals("admin123")) {
        // Jika login sebagai admin
        menuAdmin tampilMenuAdmin = new menuAdmin();
        tampilMenuAdmin.setVisible(true);
        this.dispose();
    } else {
        // Jika login gagal
        JOptionPane.showMessageDialog(this, "Nama pengguna atau kata sandi salah!");
    }
    }//GEN-LAST:event_masukBTActionPerformed

    private void daftarLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarLBMouseClicked

        FormLogin.this.dispose();

        // membuat instance baru dari from Register dan menampilkannya
        new FormRegister().setVisible(true);
    }//GEN-LAST:event_daftarLBMouseClicked

    private void sembunyiKatsanLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sembunyiKatsanLBMouseClicked
        lihatKatsanLB.setVisible(true);
        sembunyiKatsanLB.setVisible(false);
        kataSandiTF.setEchoChar('*');
    }//GEN-LAST:event_sembunyiKatsanLBMouseClicked

    private void lihatKatsanLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatKatsanLBMouseClicked
        lihatKatsanLB.setVisible(false);
        sembunyiKatsanLB.setVisible(true);
        kataSandiTF.setEchoChar((char)0);
    }//GEN-LAST:event_lihatKatsanLBMouseClicked

    private void kataSandiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kataSandiTFActionPerformed

    }//GEN-LAST:event_kataSandiTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private JPanelGradient.JPanelGradient jPanelGradient1;
    private javax.swing.JPasswordField kataSandiTF;
    private javax.swing.JLabel lihatKatsanLB;
    private javax.swing.JButton masukBT;
    private javax.swing.JTextField namaPenggunaTF;
    private border.panelround panelround1;
    private border.panelround panelround2;
    private javax.swing.JLabel sembunyiKatsanLB;
    // End of variables declaration//GEN-END:variables
}
